### ISSUE TITLE
query about models

### ISSUE THREAD

**Issue by af00731** [SnailTyan/caffe-model-zoo#4]
Hi,

 I want to ask that are your models all trained on Imagenet data? as I have checked the caffe inception v3 prototxt and it has output size 3. for imagenet it should be 1000. I just want to be sure about it..

I am also getting error while using the model for training. error states as:

 math_functions.cu:79] Check failed: error == cudaSuccess (74 vs. 0)  misaligned address
*** Check failure stack trace: ***
    @     0x7f4eb42265cd  google::LogMessage::Fail()
    @     0x7f4eb4228433  google::LogMessage::SendToLog()
    @     0x7f4eb422615b  google::LogMessage::Flush()
    @     0x7f4eb4228e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f4eb4a23cba  caffe::caffe_gpu_memcpy()
    @     0x7f4eb4a0536d  caffe::SyncedMemory::gpu_data()
    @     0x7f4eb484e7b2  caffe::Blob<>::gpu_data()
    @     0x7f4eb4a71130  caffe::BiasLayer<>::Backward_gpu()
    @     0x7f4eb4a3a519  caffe::ScaleLayer<>::Backward_gpu()
    @     0x7f4eb49efde8  caffe::Net<>::BackwardFromTo()
    @     0x7f4eb49efe3f  caffe::Net<>::Backward()
    @     0x7f4eb486f384  caffe::Solver<>::Step()
    @     0x7f4eb486ff1a  caffe::Solver<>::Solve()
    @           0x40e57b  train()
    @           0x40a6fd  main
    @     0x7f4eb29bc830  __libc_start_main
    @           0x40b159  _start
    @              (nil)  (unknown)

Thanks in advance

**Comment by SnailTyan** [comment]
@af00731  No, I trained models on my own dataset.
